
<!-- Generated by PHPWord -->
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>PHPWord</title>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
w\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>	
	
	
<style>
p.MsoFooter, li.MsoFooter, div.MsoFooter
{
    margin:0in;
    margin-bottom:.0001pt;
    mso-pagination:widow-orphan;
    tab-stops:center 3.0in right 6.0in;
    font-size:12.0pt;
}	
	
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-priority:1;
	mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-parent:"";
	margin:0in;
	margin-bottom:.0001pt;
	mso-pagination:none;
	font-size:10.0pt;
	font-family:"Calibri","sans-serif";
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:Calibri;
	mso-fareast-theme-font:minor-latin;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;}

@page Section1
	{size:7.5in 7.5in;
	margin:0in 0in 0in 0in;
	mso-header-margin: 0in;
	mso-footer-margin: 0in;
	mso-header: h1;
    mso-footer: fr1;	
	mso-paper-source:0;}
div.Section1
	{page:Section1;}
	
@page FrontpageSection
	{size:7.5in 7.5in;
	margin:0in 0in 0in 0in;
	mso-header-margin: 0in;
	mso-footer-margin: 0in;
	mso-header: frh1;
    mso-footer: frf1;	
	mso-paper-source:0;}
div.FrontpageSection
	{page:FrontpageSection;}	
	
@page contentSection
	{size:7.5in 9.5in;
	margin:0in 0in 0in 0in;
	mso-header-margin: 0in;
	mso-footer-margin: 0in;
	mso-header: h1;
    mso-footer: cf1;	
	mso-paper-source:0;}
div.contentSection
	{page:contentSection;}
	
@page emptySection
	{size:7.5in 7.5in;
	margin:6.5in 0in 0in 0in;
	mso-header-margin: 0in;
	mso-footer-margin: 0in;
	mso-header: h1;
    mso-footer: esf1;	
	mso-paper-source:0;}
div.emptySection
	{page:emptySection;}	
	

@page summerySection
	{ size:7.5in 7.5in;
    margin:50.0pt 19.0pt 0in 19.0pt;;
    mso-header-margin:0in;
    mso-header:h1;
    mso-footer:f1;
    mso-footer-margin:0in;
    mso-paper-source:0;}
div.summerySection
	{page:summerySection;}
	
	
@page contentImagesection
	{size:7.5in 7.5in;
	margin:0in 0in 0in 0in;
	mso-header-margin: 0in;
	mso-footer-margin: 0in;
	mso-header: h1;
    mso-footer: if1;	
	mso-paper-source:0;}
div.contentImagesection
	{page:contentImagesection;}	

@page itinerarySection
	{size:7.5in 8in;
	margin:0in 0in 0in 0in;
	mso-header-margin: 0in;
	mso-footer-margin: 0in;
	mso-header: ith1;
    mso-footer: itf1;	
	mso-paper-source:0;}
div.itinerarySection
	{page:itinerarySection}	

@page emptypagecolorSection
	{size:7.5in 7.5in;
	margin:0in 0in 0in 0in;
	mso-header-margin: 0in;
	mso-footer-margin: 0in;
	mso-header: epch1;
    mso-footer: epcf1;	
	mso-paper-source:0;}
div.emptypagecolorSection
	{page:emptypagecolorSection;}
	
@page detailitinerarysection
	{size:7.5in 8in;
	margin:0in 0in 0in 0in;
	mso-header-margin: 0in;
	mso-footer-margin: 0in;
	mso-header: dtfh1;
    mso-footer: dtf1;	
	mso-paper-source:0;}
div.detailitinerarysection
	{page:detailitinerarysection;}
	
	
@page travelagentsection
	{size:7.5in 7.5in;
	margin:0in 0in 0in 0in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;
	mso-header: tah1;
    mso-footer: taf1;	
	mso-paper-source:0;}
div.travelagentsection
	{page:travelagentsection;}
	
 table#hrdftrtbl
   {
    margin:0in 0in 0in 900in;
   
    overflow:hidden;
    }	
	
</style>
<xml>
<w:WordDocument>
<w:View>Print</w:View>
<w:Zoom>100</w:Zoom>
<w:DoNotOptimizeForBrowser/>
</w:WordDocument>
</xml>
</head>
<body>
<?php echo $data; ?>
</body>
</html>	